FROM debian:trixie-slim as build

ARG DEBIAN_FRONTEND=noninteractive

#SHELL ["/bin/bash", "-c"]
RUN rm /bin/sh \
  && ln -s /bin/bash /bin/sh

# install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests ca-certificates git curl libssl-dev zlib1g-dev \
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

# install Node.js
ENV NODE_VERSION=24.12.0
ENV HOME="/root"
ENV PATH="$HOME/.nvm/versions/node/v$NODE_VERSION/bin/:$PATH"
RUN git clone --depth 1 https://github.com/nvm-sh/nvm.git ~/.nvm \
  && source $HOME/.nvm/nvm.sh \
  #&& echo "\nexport NVM_DIR=\"$HOME/.nvm\"\n[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"\n[ -s \"$NVM_DIR/bash_completion\" ] && \. \"$NVM_DIR/bash_completion\"" >> ~/.bash_rc \
  && nvm --version \
  && nvm install $NODE_VERSION \
  && which node \
  && node --version \
  && npm --version \
  && npm install --global yarn \
  && which yarn \
  && yarn --version \
  && npm update -g npm

WORKDIR /react-app

RUN node -v
RUN npm -v
RUN npx -v

RUN npm init react-app /react-app \
  && npm install --save-dev web-vitals \
  && npm view react version

RUN sed -i "s% return (% const searchParams = new URLSearchParams(window.location.search);\n console.log(searchParams.get('username'))\n\n return (%g" /react-app/src/App.js
RUN sed -i "s%Edit <code>src/App.js</code> and save to reload.%Hello {searchParams.get('username')}!%g" /react-app/src/App.js
RUN sed -i "s%import './App.css';%import React from 'react';\nimport './App.css';%g" /react-app/src/App.js
RUN sed -i "s%Learn React%Learn React!<br />Version: {React.version}%g" /react-app/src/App.js

RUN yarn run build

FROM docker.io/debian:trixie-slim

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests gnupg2 ca-certificates curl nginx openssl libcap2-bin \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Allow non-root nginx to bind to privileged ports (80/443)
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx

# Check Nginx version
RUN nginx -v

# Configure Nginx: Copy custom configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Create a custom non-root user
RUN groupadd -g 101 nginx \
  && useradd -u 1001 -g nginx -s /sbin/nologin -M nginx

RUN mkdir /etc/certs \
  && openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout /etc/certs/privkey.pem -out /etc/certs/cert.pem -subj '/C=EU/ST=DE/L=example/O=graphql/CN=localhost'

# Copy application files
COPY --from=build /react-app/build /usr/share/nginx/html

# Change ownership of Nginx directories
RUN mkdir -p /var/run/nginx \
  && touch /run/nginx.pid \
  && chown -R nginx:nginx /var/www /var/log/nginx /etc/certs /var/lib/nginx /var/run/nginx /run/nginx.pid

# Expose ports
EXPOSE 80 443

# Switch to non-root user
USER nginx

HEALTHCHECK --interval=35s --timeout=4s CMD curl --fail --insecure https://localhost:443/health || exit 1

# Default command to start
CMD ["nginx", "-g", "daemon off;"]
