FROM debian:trixie-slim as build-env

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
    && apt install -y --no-install-recommends --no-install-suggests curl \
    && apt install -y --no-install-recommends --no-install-suggests openjdk-21-jdk maven \
    && rm -rf "/var/lib/apt/lists/*" \
    && rm -rf /var/cache/apt/archives

ARG USER=quarkus
RUN useradd --create-home --shell /bin/bash $USER
ARG HOME="/home/$USER"
WORKDIR $HOME
USER $USER

RUN curl -Ls https://sh.jbang.dev/ --output jbang.bash \
    && echo "229dfd76ab1ac0753ac8eed6c81c24619c83d6a194de995910a0aa485aabd14fc8014db4216d9bababb0d68410194145ec1af8ae19b81132f178ff23ed3aed77 jbang.bash" > jbang.bash.sha512 \
    && sha512sum -c jbang.bash.sha512 \
    && cat jbang.bash | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/ \
    && cat jbang.bash | bash -s - app install --fresh --force quarkus@quarkusio

ENV PATH="/home/$USER/.jbang/bin:${PATH}"

RUN quarkus create app todo-app \
    --extension='smallrye-graphql,hibernate-orm-panache,jdbc-postgresql,resteasy-reactive' \
    && cd todo-app

WORKDIR "/home/$USER/todo-app"

COPY Todo.java ./src/main/java/org/acme/Todo.java
COPY TodoResource.java ./src/main/java/org/acme/TodoResource.java
COPY application.properties ./src/main/resources/application.properties

RUN ./mvnw test --fail-at-end

EXPOSE 8888

ENV QUARKUS_HTTP_PORT="8888"
ENV QUARKUS_HTTP_HOST="0.0.0.0"

#CMD [ "quarkus", "dev" ]

ENV QUARKUS_HTTP_CORS="true"
ENV QUARKUS_HTTP_CORS_ORIGINS="*"

CMD [ "./mvnw", "quarkus:run" ]

HEALTHCHECK CMD curl -f "http://localhost:8888/graphql/schema.graphql" || exit 1
