FROM debian:trixie-slim as build-env

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y \
  # Install PostgreSQL
  && apt install -y --no-install-recommends --no-install-suggests postgresql postgresql-contrib postgresql-client \
  # make image smaller
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

# Set environment variables
ENV POSTGRES_USER=postgres \
  POSTGRES_DB=postgres \
  POSTGRES_PASSWORD=postgres \
  PGDATA=/var/lib/postgresql/data

# Create data directory
RUN mkdir -p "$PGDATA" && \
  chown -R postgres:postgres "$PGDATA" && \
  chmod 700 "$PGDATA"

# Copy custom configuration (optional)
# COPY postgresql.conf /etc/postgresql/postgresql.conf

# Switch to postgres user
USER postgres

# Initialize database cluster
RUN /usr/lib/postgresql/17/bin/initdb -D /var/lib/postgresql/data && \
  echo "listen_addresses = '*'" >> /var/lib/postgresql/data/postgresql.conf && \
  echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf

VOLUME ["/var/lib/postgresql/data"]

# Expose PostgreSQL port
EXPOSE 5432

# Initialize database and start PostgreSQL
CMD ["/usr/lib/postgresql/17/bin/postgres", "-D", "/var/lib/postgresql/data"]

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD pg_isready -U $POSTGRES_USER || exit 1
